name: Claude Review - Path Specific

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      # Only run when specific paths are modified
      - "src/**/*.js"
      - "src/**/*.ts"
      - "api/**/*.py"
      # You can add more specific patterns as needed

jobs:
  claude-review-paths:
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write  # Required for OIDC authentication when using GitHub App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Claude Code Review
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: "60"
          direct_prompt: |
            Please review this pull request focusing on the changed files.
            Provide feedback on:
            - Code quality and adherence to best practices
            - Potential bugs or edge cases
            - Performance considerations
            - Security implications
            - Suggestions for improvement

            Since this PR touches critical source code paths, please be thorough
            in your review and provide inline comments where appropriate.
